### ISSUE TITLE
AssertionError z_hat_indices_restored not equal z_hat_indices

### ISSUE THREAD

**Issue by NiccoloNiccoli** [Nikolai10/PerCo#3]
I tried running the *Compression* cell in `PerceptualCompression.ipynb` using the 0.0313bpp model.
However, I get an AssertionError telling me that z_hat_indices_restored is not equal to z_hat_indices (at line 247 of `compression_utils.py`).

What am I doing wrong?

**Comment by Nikolai10** [comment]
Dear @NiccoloNiccoli,

thanks for your interest! 

We have been unable to reproduce the error. Have you updated the [target-rate](https://github.com/Nikolai10/PerCo/blob/master/src/config.py#L31) from
`target_rate = 0.1250` to `target_rate = 0.0313`?

**Comment by NiccoloNiccoli** [comment]
Thank you! I did not change the parameter before. Now that I have changed it, it works fine!
