### ISSUE TITLE
request for requirements.txt 

### ISSUE THREAD

**Issue by xuyang-C** [Nikolai10/PerCo#4]
Impressive work! 
Could you please release the requirements.txt? I got ValueError when I attempted to run compression_utils,py: backend must be an instance of einx backend backend

**Comment by Nikolai10** [comment]
Hello @xuyang-C, 

we have added the requirements [here](https://github.com/Nikolai10/PerCo/blob/master/requirements.txt).

The file was generated from our [tutorial version using Google Colab](https://colab.research.google.com/drive/19IwzyVSTSMK-qQrzFBpV8PjCC10k1cTP?usp=sharing), after Section "Install Dependencies":

`!pip freeze > /content/PerCo/requirements.txt`

Hope this helps!
