### ISSUE TITLE
Request for more checkpoints and experimental details

### ISSUE THREAD

**Issue by cucNaifuXue** [Nikolai10/PerCo#7]
Hi,
Thanks for your impressive contributions. Here I have two questions about this project.

1. Can you release more checkpoints? Especially the model between 0.0019bpp and 0.0313bpp.

2. In script src/compression_utils.py, I have noticed that when evaluating the model, all images are resized to an 512x512 patch: 
  ```python
  def read_png(filename):
      """Loads a PNG image file."""
      img = Image.open(filename).convert('RGB')
      img = TR.functional.resize(img, (512, 512), Image.BICUBIC)
      img_tensor = ToTensor()(img)  # img_tensor in [0, 1]
  return img_tensor
  ```

I am confused about this design for it changes the aspect ratio of the image. Is this design follows the implementation in its original paper?

In your experiment, when testing model on MSCOCO-30k dataset, are all images resized to 512x512?

Thank you very much for your time and reply!

**Comment by Nikolai10** [comment]
Dear @cucNaifuXue, 

thanks for your interest!

Regarding 2: the pre-processing/ resize operation was directly provided by the authors. In our e-mail chat, we also briefly discussed this detail (obviously, this is not an optimal choice, as it changes the aspect ratio. A solution was briefly described in their paper/ section Limitations: https://arxiv.org/pdf/2310.10325, based on: https://arxiv.org/abs/2305.18231). So yes, for MSCOCO-30k, all images are resized to 512x512, following the official configuration.

Regarding 1: We will provide all model checkpoints, once the experiments are done (this may take a while). For now, however, we only provide a subset corresponding to the lowest, highest and intermediate bit-rate models.

Hope this helps,
Nikolai

**Comment by cucNaifuXue** [comment]
Thanks for your reply. It helps me a lot.
