### ISSUE TITLE
Reconstruction isn't working

### ISSUE THREAD

**Issue by yahya280101** [Nikolai10/PerCo#9]
Thank you so much for the phenomenal work! I really enjoyed reading about the idea. 

I was just trying to try the model with pre-trained checkpoints, and it seems I am reconstructing it wrong for some reason. I followed the tutorial exactly but I skipped the training part. 

Do you have any idea why this might have happened? 

Thanks a lot!

![kodim11](https://github.com/user-attachments/assets/3f1b1d8f-e885-4dcb-8eea-95d2677cb44d)
![kodim2](https://github.com/user-attachments/assets/ff333ded-b128-438e-879a-62737d959f12)

**Comment by Nikolai10** [comment]
Hello @yahya280101,

thanks for your interest.

Which pre-trained model did you use for generating the reconstruction? Depending on the bit-rate, you need to update the [config](https://github.com/Nikolai10/PerCo/blob/master/src/config.py#L31) to the correct target-rate.

Also note: by default all images are resized to 512x512; to preserve the aspect ratio, uncomment line
https://github.com/Nikolai10/PerCo/blob/master/src/compression_utils.py#L79.

Let me know if this works.
Nikolai

**Comment by yahya280101** [comment]
Thanks a lot. It is working. btw a-followup question: do you have any idea why the model reconstructs images with people's faces a bit washed out? Is this intentional, or should I try a different input/setup?

**Comment by Nikolai10** [comment]
Great! Closing this issue.

> btw a-followup question: do you have any idea why the model reconstructs images with people's faces a bit washed out? Is this intentional, or should I try a different input/setup?

Please see issue #10; feel free to discuss your observations there.
